<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.6.39">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Ashleigh Wilson">

<title>Understanding Workplace Dynamics through Organizational Network Analysis: A Demonstration using Game of Thrones Data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="GOT_Season6_files/libs/clipboard/clipboard.min.js"></script>
<script src="GOT_Season6_files/libs/quarto-html/quarto.js"></script>
<script src="GOT_Season6_files/libs/quarto-html/popper.min.js"></script>
<script src="GOT_Season6_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="GOT_Season6_files/libs/quarto-html/anchor.min.js"></script>
<link href="GOT_Season6_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="GOT_Season6_files/libs/quarto-html/quarto-syntax-highlighting-e26003cea8cd680ca0c55a263523d882.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="GOT_Season6_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="GOT_Season6_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="GOT_Season6_files/libs/bootstrap/bootstrap-973236bd072d72a04ee9cd82dcc9cb29.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script src="GOT_Season6_files/libs/kePrint-0.0.1/kePrint.js"></script>
<link href="GOT_Season6_files/libs/lightable-0.0.1/lightable.css" rel="stylesheet">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Understanding Workplace Dynamics through Organizational Network Analysis: A Demonstration using Game of Thrones Data</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Ashleigh Wilson </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction-to-ona" class="level1">
<h1>Introduction to ONA</h1>
<p>Think about how work actually gets done. It’s not just about following the official company structure. People ask colleagues for advice, collaborate on projects across teams, and share information informally. These hidden connections are vital for getting things done, sparking new ideas, and building our company culture.</p>
<p><strong>Organizational Network Analysis (ONA)</strong> is simply a tool to see and understand this hidden network. It helps us answer questions like:</p>
<ul>
<li><strong>Who really talks to whom?</strong> Where does information flow quickly, and where does it get stuck?</li>
<li><strong>Who works well together?</strong> Are there teams or groups that are cut off from others?</li>
<li><strong>Who are the key “go-to” people?</strong> These might not be managers, but they are central to getting work done and influencing others.</li>
<li><strong>Are there hidden groups or cliques?</strong> ONA can show us natural working groups we didn’t know about.</li>
</ul>
<p>ONA helps companies make informed decisions to boost productivity, support talent, manage change, and build a more equitable workplace. Since real employee data is sensitive, I used Game of Thrones (GOT) character interactions to demonstrate the method.</p>
</section>
<section id="mapping-connections-using-game-of-thrones-data" class="level1">
<h1>Mapping Connections Using Game of Thrones Data</h1>
<section id="the-data" class="level2">
<h2 class="anchored" data-anchor-id="the-data">The Data</h2>
<p>I used data about who interacted with whom in Game of Thrones Season 6. (Data source: <a href="https://github.com/mathbeveridge/gameofthrones">here</a>). This includes:</p>
<ul>
<li><strong>Characters (Nodes):</strong> A list of people (like our employees).</li>
<li><strong>Interactions (Edges):</strong> Records of which characters interacted, and how often (like emails, meetings, or working together). - The more interactions, the stronger the connection (Weight).</li>
</ul>
<p>Packages used:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidygraph)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggraph)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(igraph)</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(kableExtra)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Loading the Data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a>got_s6_edges <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/got-s6-edges.csv"</span>)</span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>got_s6_nodes <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"data/got-s6-nodes.csv"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Quick Look at the Data:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(got_s6_edges)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 542
Columns: 4
$ Source &lt;chr&gt; "JON", "MISSANDEI", "TYRION", "ARYA", "DAVOS", "GREY_WORM", "DA…
$ Target &lt;chr&gt; "SANSA", "TYRION", "VARYS", "JAQEN", "MELISANDRE", "TYRION", "J…
$ Weight &lt;dbl&gt; 151, 88, 86, 83, 82, 81, 80, 80, 76, 76, 72, 69, 66, 64, 60, 57…
$ Season &lt;dbl&gt; 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, …</code></pre>
</div>
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(got_s6_nodes)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 142
Columns: 2
$ Id    &lt;chr&gt; "AERON", "AERYS", "ALLISER_THORNE", "AREO", "ARTHUR", "ARTHUR_CH…
$ Label &lt;chr&gt; "Aeron", "Aerys", "Alliser", "Areo", "Arthur", "Arthur (child)",…</code></pre>
</div>
</div>
<ul>
<li><p><strong>Interactions:</strong> <code>Source</code> (who started), <code>Target</code> (who received), <code>Weight</code> (how strong), <code>Season</code>.</p></li>
<li><p><strong>Characters:</strong> <code>Id</code>, <code>Label</code> (name).</p></li>
</ul>
<p>This network has 142 characters (nodes) and 542 connections (edges).</p>
<p>Let’s see how much interaction happened overall:</p>
<div class="cell">
<div class="cell-output-display">
<table class="lightable-classic caption-top table table-sm table-striped small" data-quarto-postprocess="true">
<thead>
<tr class="header">
<th style="text-align: left;" data-quarto-table-cell-role="th">Total Interactions</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">5795</td>
</tr>
</tbody>
</table>


</div>
</div>
<p>There were 5795 weighted interactions – a lot of activity!</p>
<hr>
</section>
<section id="what-to-look-for-in-a-network" class="level2">
<h2 class="anchored" data-anchor-id="what-to-look-for-in-a-network">What To Look For in a Network</h2>
<p>When looking at a network map, we want to focus on a few key things:</p>
<ul>
<li><p><strong>Groups (Communities):</strong> People often form groups that interact a lot internally, but less with outsiders. Think of departments, project teams, or even lunch groups. Finding these helps us see natural working units and potential barriers between groups (“silos”).</p></li>
<li><p><strong>Important People (Centrality):</strong> Some people are more important in the network than others. We measure this in a few ways:</p></li>
<li><p><strong>Most Connected (Degree):</strong> Who has the most direct connections? These people are local hubs of activity.</p></li>
<li><p><strong>Key Connectors (Betweenness):</strong> Who sits <em>between</em> different groups and connects people who wouldn’t otherwise be connected? These are vital bridges for information flow. Losing them can break the network apart. They can also become bottlenecks if they’re too busy.</p></li>
<li><p><strong>Influencers (PageRank):</strong> Who is connected to <em>other</em> well-connected people? These individuals often have broad influence and access to information across the network.</p></li>
</ul>
<p><strong>Finding these Patterns:</strong> We can calculate these scores for everyone in the network.</p>
</section>
</section>
<section id="what-the-map-showed" class="level1">
<h1>What The Map Showed</h1>
<section id="the-big-picture" class="level2">
<h2 class="anchored" data-anchor-id="the-big-picture">The Big Picture</h2>
<p>Let’s draw the map to see the overall structure.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GOT_Season6_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>What this Map Shows:</strong></p>
<ul>
<li><p><strong>Groups (Colors):</strong> The different colors show distinct groups. Do these match our departments? Are some groups isolated with few links to others (silos)?</p></li>
<li><p><strong>Key Connectors (Big Dots):</strong> People like Sansa, Daenerys, Tyrion are big dots – they connect different groups. In our company, who are these vital bridges? We need to support them, but also ensure they aren’t bottlenecks.</p></li>
<li><p><strong>Strong Relationships (Thick Lines):</strong> Thick lines show frequent interaction. Are the right people talking? Are there weak links where we expect strong ones?</p></li>
<li><p><strong>Influencers (Big Labels):</strong> Characters with bigger labels are connected to other important people. In our workplace, these could be leaders, experts, or trusted advisors.</p></li>
</ul>
<section id="whos-important-in-each-group" class="level3">
<h3 class="anchored" data-anchor-id="whos-important-in-each-group">Who’s Important in Each Group?</h3>
<p>Let’s find the most directly connected person (highest “Degree” score) within each colored group.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Most Connected Person (by Direct Ties) in each Group:"</code></pre>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "Sansa"   "Tyrion"  "Cersei"  "Ned"     "Arya"    "Ellaria" "Brynden"
[8] "Sam"     "Lem"    </code></pre>
</div>
</div>
<p>The analysis picks out key figures in different storylines: Sansa (North), Daenerys (Essos), Cersei (King’s Landing), etc. These are the main hubs within their circles.</p>
<p><strong>What This Means:</strong> Finding the most connected person in each team or department helps me identify:</p>
<ul>
<li><p><strong>Local Leaders:</strong> Maybe the official manager, or maybe just the informal go-to person in that group.</p></li>
<li><p><strong>Information Hubs:</strong> They likely know what’s going on <em>within</em> their group.</p></li>
<li><p><strong>Good Representatives:</strong> They might be good people to ask for the group’s opinion.</p></li>
</ul>
</section>
<section id="map-highlighting-the-key-people-in-each-group" class="level3">
<h3 class="anchored" data-anchor-id="map-highlighting-the-key-people-in-each-group">Map Highlighting the Key People in Each Group</h3>
<p>Let’s redraw the map, but only label these key group figures.</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="GOT_Season6_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p><strong>What This Shows:</strong></p>
<p>This map makes it easier to see how the main hubs of different teams or groups are connected (or not connected) to each other. It highlights potential cross-team leaders or critical links between departments.</p>
</section>
</section>
</section>
<section id="ona-deia-key-implications" class="level1">
<h1>ONA &amp; DEIA: Key Implications</h1>
<p>Looking at network maps like the Game of Thrones example can give organizations powerful insights into fairness and inclusion within their workplace. Here’s how ONA can help a company understand and improve Diversity, Equity, Inclusion, and Accessibility (DEIA):</p>
<ul>
<li><p><strong>Finding Hidden Diverse Influencers:</strong> ONA can reveal influential people and key connectors who belong to underrepresented groups but might not hold senior titles. Are these individuals recognized within the organization? Are they receiving adequate support? Identifying them helps ensure diverse voices contribute to decision-making and can highlight pathways for creating fairer opportunities for growth.</p></li>
<li><p><strong>Checking for Fair Access to Information:</strong> Does important information reach everyone equitably, or are some demographic groups systematically excluded? ONA can map whether people from underrepresented backgrounds are consistently outside the main information flows, potentially missing out on opportunities or feeling isolated. This helps identify and address communication barriers.</p></li>
<li><p><strong>Seeing if Teams are Truly Inclusive:</strong> ONA can illustrate whether work groups and teams integrate people from different backgrounds, or if individuals tend to cluster with others similar to themselves (homophily). It helps visualize if employees from underrepresented groups are central to team networks or are positioned on the periphery.</p></li>
<li><p><strong>Understanding the Impact When Diverse Talent Leaves:</strong> If a key connector from an underrepresented group departs, who else within the network loses connections? ONA can show if their departure disproportionately isolates others from similar backgrounds, highlighting the need for stronger retention strategies, supportive networks, and broader relationship-building initiatives for everyone.</p></li>
<li><p><strong>Making Onboarding Fair for Everyone:</strong> Are new hires from diverse backgrounds integrating into the organizational network as quickly and effectively as others? ONA can track this integration process. If certain groups consistently take longer to build connections, it may signal biases or areas where onboarding processes need to be made more intentionally inclusive.</p></li>
<li><p><strong>Including Diverse Voices in Decisions &amp; Change:</strong> When planning organizational changes, are perspectives gathered equitably? ONA helps identify trusted influencers across various employee groups. Engaging these diverse influencers can lead to change initiatives that are more effective, sustainable, and perceived as fairer by the workforce.</p></li>
<li><p><strong>Spotting Hidden Barriers:</strong> The informal network revealed by ONA might uncover systemic inequities hidden by the formal organizational chart. For instance, ONA might show that opportunities to join high-profile projects are disproportionately allocated to certain demographic groups. This data provides a basis for examining and addressing practices to create more equitable opportunities.</p></li>
</ul>
<p>By utilizing ONA with a focus on DEIA, organizations can move beyond assumptions and gather objective data about inclusion, helping to build workplaces where everyone feels connected, valued, and has equitable opportunities to succeed.</p>
</section>
<section id="recommendations-for-organizations" class="level1">
<h1>Recommendations for Organizations</h1>
<p>Companies can use ONA insights to improve effectiveness and DEIA:</p>
<ol type="1">
<li><p><strong>Conduct ONA Ethically:</strong> Periodically map networks (via surveys or anonymized data with strict privacy controls) to track dynamics.</p></li>
<li><p><strong>Support Diverse Connectors:</strong> Recognize, support, and develop influential employees from underrepresented groups.</p></li>
<li><p><strong>Bridge Gaps:</strong> Actively foster connections between isolated groups or individuals, especially across demographic lines.</p></li>
<li><p><strong>Mitigate Key Person Risk:</strong> Plan for succession and knowledge sharing, particularly for diverse individuals in critical bridging roles.</p></li>
<li><p><strong>Integrate ONA into DEIA Strategy:</strong> Use network data to inform initiatives and measure progress on inclusion goals.</p></li>
</ol>
</section>
<section id="project-limitations-to-note" class="level1">
<h1>Project Limitations to Note</h1>
<ul>
<li><strong>Example Data:</strong> In this project, I used Game of Thrones data as a substitute for real workplace data. While illustrative, character interactions in a fictional series are driven by different factors than professional interactions in an organization.</li>
<li><strong>Data Collection Challenges:</strong> Implementing ONA in a real organization requires careful planning around data collection methods (surveys, passive data), ensuring data quality, and navigating ethical considerations and privacy regulations.</li>
<li><strong>Static Snapshot:</strong> The analysis presented here represents a single point in time (Season 6). Real organizational networks are dynamic and change constantly. ONA provides the most value when used to track trends over time.</li>
</ul>
</section>
<section id="conclusion" class="level1">
<h1>Conclusion</h1>
<p>Organizational Network Analysis offers a valuable method for looking beyond formal structures to understand the real, informal networks that drive communication, collaboration, and influence within a company. As I demonstrated using the Game of Thrones dataset, ONA techniques can identify key structures, influencers, and potential bottlenecks.</p>
<p>When viewed through a DEIA lens, ONA can provide objective data to help organizations build more equitable, inclusive, and ultimately more effective workplaces by ensuring everyone is connected and valued.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>